apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
      - name: nfs-client-provisioner
        env:
        - name: NFS_SERVER
          value: THIS_SHOULD_BE_SET_AT_INSTALL_TIME
        - name: NFS_PATH
          value: THIS_SHOULD_BE_SET_AT_INSTALL_TIME
      volumes:
      - name: nfs-client-root
        nfs:
          server: THIS_SHOULD_BE_SET_AT_INSTALL_TIME
          path: THIS_SHOULD_BE_SET_AT_INSTALL_TIME
